### ISSUE TITLE
404 download for api/v1/items

### ISSUE THREAD

**Issue by ressl** [hay-kot/homebox#657] opened 2023-12-08 14:56 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Version: v0.10.2 ~ Build: 8cc0f302919758044dc9ff4dc785c452364dc715

### What is the issue you are experiencing?

It seems the endpoint api/v1/items is listed in all documentation I could find as api/v1/items, which ends up in 404.

The only way I managed to see the issue is by finding the exact route in the source code, where it was listed as /v1/asset. Maybe it was actually intended to be assets (plural) and the documentation is the one that's correct?

I would make a quick MR, but I'm not sure how the documentation is getting generated, if it comes from the file comments or somewhere else - and as I said, I'm not even sure what's the correct endpoint in the end.

Look like the same issue as #515

### How can the maintainer reproduce the issue?

Try to get an asset using the API and the documentation by calling api/v1/items/{id}/attachments/{id} , get 404.

### Deployment

Other

### Deployment Details

TrueNas Scale via truecharts (Kubernetes, with ingress Traefik)

**Comment by Uncanny5180** [comment] 2023-12-23 13:13
Are you using this behind a reverse proxy? I found similar behavior using the site behind nginx proxy manager, however if I go direct to the docker server ip:port, the site behaves as expected. I was trying to use the export function, which throws the 404 error for the api/v1/assets link.

**Comment by lumio** [comment] 2023-12-23 14:28
@Uncanny5180 I ran into the same issue. The 404 seems to be part of homebox. However, I only get it when run through nginx proxy manager.

Did you find any workaround yet?

**Comment by Uncanny5180** [comment] 2023-12-23 15:25
> @Uncanny5180 I ran into the same issue. The 404 seems to be part of homebox. However, I only get it when run through nginx proxy manager.
> 
> Did you find any workaround yet?
> 
> I did play around a little bit, accessing the requested item directly. Then swapping out the domain name. I got the same issue, however with a hard refresh, it works fine. Refreshing again, brings up the 404.

Not as of yet outside of using the ip:port.... but I've had it installed for all of 10 minutes earlier this morning. My biggest concern was ensuring that, ok I entered all this crap how do I hand it off to the insurance company? I

**Comment by ressl** [comment] 2023-12-24 22:00
Yes, I use it on Kubernetes, with ingress Traefik.

**Comment by dsw5022** [comment] 2023-12-25 04:32
Could this be related to #659?  I seem to get a similar result; if I have an open session I'll end up with a 404, but forcing a re-authentication seems to solve the issue.

**Comment by lmaced0** [comment] 2023-12-27 01:55
Having the same issue. Looks like when loading the page using traefik I get these errors in the console. Things work ok when loading directly from IP:port.

<img width="1524" alt="Screenshot 2023-12-26 at 6 51 28 PM" src="https://github.com/hay-kot/homebox/assets/83371481/16d02512-fff1-4d60-8bea-34a35d4c0106">
<img width="1524" alt="Screenshot 2023-12-26 at 6 51 31 PM" src="https://github.com/hay-kot/homebox/assets/83371481/8161935b-5cb4-41db-808b-5dc04c367e57">

**Comment by hay-kot** [comment] 2024-01-04 21:15
I think this is fixed in the latest release v0.10.3. Could you try and replicate the issue on there?

**Comment by Uncanny5180** [comment] 2024-01-04 21:24
> I think this is fixed in the latest release v0.10.3. Could you try and replicate the issue on there?

Just updated to 0.10.3, tools > export inventory > 404. Running in docker behind nginx proxy manager.

**Comment by hay-kot** [comment] 2024-01-04 21:32
Im almost certain this has been fixed. 

Can you try clearing your cache and/or removing the service worker for the site in your browser 

Does this happen for you in the Demo site?

**Comment by Uncanny5180** [comment] 2024-01-04 21:34
> Im almost certain this has been fixed.
> 
> Can you try clearing your cache and/or removing the service worker for the site in your browser
> 
> Does this happen for you in the Demo site?

Hm, seems you're right. I tried it out in edge and it worked fine as you said it should. But my firefox cache clears upon every close...so there shouldnt be anything stuck in there as its been 2 weeks since I touched it. But anyhow, indeed it seems to be working fine.

**Comment by lmaced0** [comment] 2024-01-04 22:01
I can confirm it's fixed for me with `v0.10.3`. Thanks!

**Comment by ressl** [comment] 2024-01-06 14:39
Version: v0.10.3 ~ Build: e8449b3a7363a6cfd5bc6151609e6d2d94b4f7d8, works for me too now. Thanks, you can close the bug.

**Closed** 2024-01-06 15:44 UTC
Labels: bug
