### ISSUE TITLE
Ability to add photos at the location level 

### ISSUE THREAD

**Issue by danielrosehilljlm** [hay-kot/homebox#762] opened 2024-02-14 22:04 UTC
### What is the problem you are trying to solve with this feature?

You can add attachments at the asset level but not at the location level.

If you could add attachments at the location level, you could:

- Append photos of the specific location to the location page (e.g. I've created some similar looking cabinets as 'locations' for asset storage. It would be nice to have a visual reference to tell them apart). 

- The appearance of the location level would also be improved.

### What is the solution you are proposing?

- Implement the ability to add photos at the location level.
- Implement cover art for locations with photographs

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment] 2024-02-15 02:19
Duplicate of

- https://github.com/hay-kot/homebox/issues/560

**Closed by hay-kot** 2024-02-15 02:19 UTC
Labels: feature-request
