### ISSUE TITLE
Option to export items

### ISSUE THREAD

**Issue by Dxvxdffm** [hay-kot/homebox#194] opened 2022-12-30 12:36 UTC
Would be useful to export items to another homebox account using the import CSV option then on the other account.

I want to keep seperate homebox accounts for different locations I'm living. For example 1 for my parents home and one for my own.
Now, when I take stuff to my own home it would be nice when I could move them also in homebox (export & import would be fine) instead to create them again on the new account.

**Comment by hay-kot** [comment] 2022-12-31 01:12
Duplicate of 

- https://github.com/hay-kot/homebox/issues/16

**Closed by hay-kot** 2022-12-31 01:12 UTC
