### ISSUE TITLE
When editing item, description and notes fields are showing the previous item's description and notes

### ISSUE THREAD

**Issue by dima-ser** [hay-kot/homebox#518] opened 2023-07-30 16:27 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

v0.9.2

### What is the issue you are experiencing?

When editing item, description and notes fields are showing the previous item's description and notes.

### How can the maintainer reproduce the issue?

Edit an item with values in either description or notes field (no need to save, just visiting the edit screen is enough). Then search for another item and edit it. The description and notes fields will show values from the previous item.
When searching another item and editing, the description and notes will now show the item before and so on.
A workaround I found is after experiencing the bug, click the "Details" tab of the item you're trying to edit, then click the "Edit" tab again. The description and notes now show correct values for the item.

### Deployment

Docker (Synology)

**Comment by agrrajag** [comment] 2023-08-01 14:34
I've seen the same happen with me. 

If I went to edit an item that was errored like this, it wouldn't let me save any modifications.

If I refreshed the page, it showed the correct information and would let me save any modifications.

**Comment by JigSawFr** [comment] 2023-08-11 13:07
Confirmed also on my side

**Comment by concr** [comment] 2023-09-09 19:08
Damn... I duped your bug. But maybe my step-by-step list helps on this topic / bug:

https://github.com/hay-kot/homebox/issues/548

**Comment by terba** [comment] 2023-11-30 09:51
Same here. Issue should be added to https://github.com/hay-kot/homebox/milestone/9 as it's a critical bug.

**Comment by hay-kot** [comment] 2024-01-04 20:55
This should be fixed. Please update to the latest and create a new issue if you've re-created the issue.

**Closed by hay-kot** 2024-01-04 20:55 UTC
Labels: bug
