### ISSUE TITLE
Recently added shows all items instead of recently added

### ISSUE THREAD

**Issue by jk** [hay-kot/homebox#342] opened 2023-03-12 12:04 UTC
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.8.2

### What is the issue you are experiencing?

On »Home« there is a widget titled with »Recently Added«. Instead of recently added items it shows all items sorted by whichever field selected truncated to 5 items. So sorting for name shows me the first 5 items starting at »A«.

### How can the maintainer reproduce the issue?

Add six or more items and sort by »Name«. 

### Deployment

Docker (Linux)

**Comment by chevdor** [comment] 2023-03-14 14:18
I did notice this issue in 0.8.2 indeed. Due to [another issue](https://github.com/hay-kot/homebox/issues/348) I ended up building a new Docker image from HEAD and the issue seems to be fixed now. I am not sure which commit fixed it but it shoudl in one of [those](https://github.com/hay-kot/homebox/compare/v0.8.2...HEAD).

**Comment by hay-kot** [comment] 2023-03-15 16:54
Looks fixed to me, am I missing something?

![CleanShot 2023-03-15 at 08 53 53](https://user-images.githubusercontent.com/64056131/225382990-f1a6eba2-acfb-4fe4-bfdd-4118e5689922.gif)

**Comment by hay-kot** [comment] 2023-03-15 18:16
> No, it's only the alphabetical first that pop in there ("[A]n item", "[B]ox",...) If you create an item named "zzz" for example, it won't appear here even though it's the most recently added :( . At least that's what happens on my end on the demo instance

Ahhhhhhhh. Got it, but confirmed thanks!

**Closed** 2023-04-02 06:01 UTC
Labels: bug
